# Optional ingress for aws
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helpdesk-llm-ingress
spec:
  rules:
  - host: REPLACE_WITH_AWS_DOMAIN
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: helpdesk-llm
            port:
              number: 80
