apiVersion: v1
kind: Service
metadata:
  name: {{ include "security-ai.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "security-ai.name" . }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 80
